version: "3.8"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    # healthcheck:
    #   test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    networks:
      - app_network

  web:
    # platform: linux/amd64
    build: .
    # command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    command: gunicorn --worker-class gevent app_parking.wsgi:application --bind 0.0.0.0:8000 --timeout 300
    # volumes:
    #   - .:/app
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB_NAME}
    # environment:
    #   - DEBUG=${DEBUG}
    #   - DJANGO_SETTINGS_MODULE=app_parking.settings
    #   - DB_NAME=${DATABASE_NAME}
    #   - DB_USER=${DATABASE_USER}
    #   - DB_PASSWORD=${DATABASE_PASSWORD}
    #   - DB_HOST=${DATABASE_HOST}
    #   - DB_PORT=${PORT_DB}
    #   - API_SECRET=${SECRET_KEY}
    #   - API_KEY=${API_KEY}
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:


volumes:
  postgres_data:
